## YAML Template.
---
services:
    config:
        container_name: "mstr-config"
        ports:
          - "8888:8080"
        image: "config:0.0.1"
        environment: 
          - SPRING_PROFILES_ACTIVE=native,docker
        healthcheck:
          test: ["CMD-SHELL", "curl -f http://config:8080/actuator/health || exit 1"]
          timeout: 10s
          retries: 10
    discovery:
        container_name: "mstr-discovery"
        depends_on:
            config: 
                condition: service_healthy
        ports:
          - "8761:8080"
        image: "discovery:0.0.1"
        environment: 
          - SPRING_PROFILES_ACTIVE=docker
        healthcheck:
          test: ["CMD-SHELL", "curl -f http://discovery:8080/actuator/health || exit 1"]
          timeout: 10s
          retries: 10
    serviceadb:
        container_name: "mstr-serviceadb"
        ##depends_on:
            ##config: 
                ##condition: service_healthy
        image: "mariadb"
        ports:
            - "3306:3306"
        restart: unless-stopped
        environment: 
            - MARIADB_USER=user
            - MARIADB_PASSWORD=user
            - MARIADB_ROOT_PASSWORD=root
        command: --init-file /data/application/init.sql
        volumes:
            - ./init.sql:/data/application/init.sql
            - db-data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            timeout: 10s
            retries: 10
    service-a:
        container_name: "mstr-servicea"
        depends_on:
            serviceadb:
                condition: service_healthy
            config: 
                condition: service_healthy
        image: "service-a:0.0.1"
        ports:
          - "81:8080"
        restart: unless-stopped
        environment: 
          - SPRING_PROFILES_ACTIVE=docker
        healthcheck:
          test: ["CMD-SHELL", "curl -f http://service-a:8080/actuator/health || exit 1"]
          timeout: 10s
          retries: 10
    gateway:
        container_name: "mstr-gateway"
        depends_on:
            service-a:
                condition: service_healthy
            config: 
                condition: service_healthy
        ports:
          - "8080:8080"
        image: "gateway:0.0.1"
        environment: 
          - SPRING_PROFILES_ACTIVE=docker
volumes:
    db-data:
